plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.google.cloud.tools.jib' version '3.5.4'
}

group = 'com.mtumilowicz'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

def dockerExecutable = 'docker'
def dockerDesktopExecutable = file('/Applications/Docker.app/Contents/Resources/bin/docker')
if (dockerDesktopExecutable.exists()) {
    dockerExecutable = dockerDesktopExecutable.absolutePath
}

jib {
    from {
        image = 'eclipse-temurin:21-jre'
    }
    to {
        image = 'spring-boot-k8s-gitops-flux-sops-workshop:latest'
        tags = ['1.0.0']
    }
    container {
        ports = ['8080']
    }
    dockerClient {
        executable = dockerExecutable
    }
}

tasks.named('test') {
    dependsOn tasks.named('jibDockerBuild')
    systemProperty 'project.root', projectDir.absolutePath
}
