apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spring-boot-k8s-gitops-flux-sops-workshop-prod

resources:
  - namespace.yaml
  - ../../base
  - secret.enc.yaml

patches:
  - path: patch-deployment.yaml

images:
  - name: spring-boot-k8s-gitops-flux-sops-workshop
    newTag: 1.0.0
