apiVersion: v1
kind: Secret
metadata:
    name: spring-boot-k8s-gitops-flux-sops-workshop-secrets
type: Opaque
stringData:
    demo-token1: ENC[AES256_GCM,data:029kYpKWGgaqv3DOKSoN5aXFYzk=,iv:cGvhEY/ZGyPwIYgXux1WVyCqqqptCmQveEbmCK2hUy0=,tag:FZItdM9EdV4D8/JpLGsx1Q==,type:str]
    demo-token2: ENC[AES256_GCM,data:bkoQUGZtD5jEKFsZTDc+LxEVyc0=,iv:cqWOp9P6gq1fco6Asp2NWHsNrMFkP+bOCE8b+FfGjsY=,tag:IaKGrmZ4IEd0qHmyvMVvrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSitaRUFPQytFc0FaUkZk
            K29VOUYwTGJ1dDk0bGRuUkhuT2J0SjlPZkMwCkdrMDVscVJWQmRrQWJJbDgxVytv
            QVkwZmVEajh1NFlzVjh4aTN2cjBRUWMKLS0tIGpaMWFKcHJmTkxVM1V5Q2xETFBv
            RktZSVpJbU01NFovT243M25GK2ZvdXcKA4ngIN/teDjhA0BrKj7idkJPXWJpG7dP
            XVSwKcpY7ZJ0WuINccKIRRNsZNR4gsXFl/vh6F36Ro+RQYMPemeQAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xkr0q0wjnys2anw236xqqzwggqu2thxzgq56x7s0gz6nlewsvqpsf0nktc
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-08-14T20:53:24Z"
    mac: ENC[AES256_GCM,data:CJyjC31iRWmnA6XpulNSDEhYxx2iOa6/m/H5mhpsPtz9DIgzPEIlP93AXxYBOtqaRjLUZdJ4cRrIPgqjLRny2VT9ybOhhTBT+vu0OkDAW5kTj7fg2ZxArGyLvxA2Dp3saYGtzOUKsXAQiu382iFTqWDFjXM3hLH7Ybycx58zwd4=,iv:pMIOqEbwvK/HTK65EWzpdkIexizQqD0AjvLYpKeinh8=,tag:S+ljfpqhuIY6kQ62AozFyg==,type:str]
    version: 3.13.3
