apiVersion: v1
kind: Secret
metadata:
    name: spring-boot-k8s-gitops-flux-sops-workshop-secrets
type: Opaque
stringData:
    demo-token1: ENC[AES256_GCM,data:h3jiV/SIQqZtx/DzQNfOarWQdw==,iv:YouzouzHwVBVI4B3jzgXT8JuGWI/RoFS0XKcFmr1zcg=,tag:3PmWtR7TRvvlm0eu4R60Bg==,type:str]
    demo-token2: ENC[AES256_GCM,data:XC/6oNJ5B9MEjWHYnyPfoHhuIA==,iv:trIjLlHyMpdKUB2imGjSXzCIqsB0iht8VEL2oUX/XEc=,tag:OGAnTTrifqJOkbHD81VNNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSHdaL3RzRkVkNHB5N21n
            ZXdxd1llc01HZW1CYW5NTm8yNEVSTmsvd3hvClo4bG41M0VuYytLZzAvMVBLVEZI
            MldPbUdFa2FQUmlOdUVpRGNOc1VtZmMKLS0tIHpiT2VzckxGRmhOU0pITzA5T1J2
            R0pyTGVEUzRWei9xcHU3SXpoWStadlEKz+sZNu2dQ+6Z1bOQHjk8QyUbrsPeY32w
            eL93LfY+EyqAPw9oxyXLbgbn7GAGhUwJfyunb4k5t6R9+PZMYErPJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r2lsff8tazyxvqtvfz7ya5anv6rte75yrvk6nlc2yyaezq8433qephwvz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNkhETXRiWjJ3Wm5EbG12
            czM2dFpZdDFDUDE0dWNlNzlmNXFkRWlVOGc0Cm5ORi9GVG5LbDdicFRVcjk4T1Vz
            MDhWWUZNOERmYW9zQks2ZVBVSHRhNUUKLS0tIFB1TklyTHN5R3NsUG5DNFhieWgz
            Q1ozeTF1YjhwZ2EzUm0wWnJ2d3hiWFEKszSeYdy4WkOJIWlaPkjUAh4g0sM3dZkN
            o0U9Ps2HuFLRbkkLzc5+jj8oyAE8vrJ4g2Qo+RSQfn6HGWrLdbMYGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18qdpstfprlz0z52gn54qwkx7zzeryfsmps77w4rnhk73hf2shvvsp3xvrl
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-08-14T20:53:24Z"
    mac: ENC[AES256_GCM,data:I2heFiIKi9892r5kQGwfnDPlSPQvT24MK61CatagqpP8yFo405UUDK5PfCZiU9eshek8rqrRrXU25DL23a2PyQTAv/YH2F9DqPweKLECDnAVpOmJ+vax6U7fKty6bwTuFt5HBZLBDXpBKjVbKMlOIRg/9aRLqBsxCTdPrqyL0jI=,iv:dI45Vpl5P/3H68N689R+8JRzfSiiIANDIgPE7qyDuwE=,tag:7B1LZDt+Xmev6rD36XhuYA==,type:str]
    version: 3.13.3
